require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

#prepare_react_native_project!

target 'example' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  platform :ios, '11.0'

  #use_frameworks!
  #use_flipper!

end
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings["ONLY_ACTIVE_ARCH"] = 'YES'
#        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ''
#        config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
#      end
#    end
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["ONLY_ACTIVE_ARCH"] = 'YES'
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = ''
#      config.build_settings['ARCHS[sdk=iphonesimulator*]'] =  `uname -m`
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
#    end
#  end